application: pyregex
version: 3
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /assets
  static_dir: assets/dist

- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.application
