application: pyregex
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /gae_admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: .*
  script: common/appenginepatch/main.py
