application: pyregex-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: webapp2
  version: latest

handlers:
- url: /assets
  static_dir: assets/dist

- url: /
  static_files: index.html
  upload: index.html

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: .*
  script: pyregex.webapp.application

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^node_modules/.*
- ^assets/bower_components/.*
- ^assets/src/.*
- ^assets/build/.*
- ^Gruntfile\.js
- ^assets/component\.json
- ^package\json
- ^lib/.*
- ^tests/.*
- ^requirements\.txt
- ^README\.md
- ^LICENSE
- ^dependencies/.*